#' Simulate an agarose gel electrophoresis
#'
#' Generates an agarose-gel-style graphic to visualize the expected
#' fragments in a PCR-RFLP assay, including a molecular weight marker and
#' the three possible genotypes: uncut homozygote, heterozygote (both
#' patterns) and cut homozygote.
#'
#' @param amplicon_size Size (bp) of the undigested amplicon.
#' @param fragment_sizes Numeric vector with the two sizes (bp) generated by
#'   complete digestion (e.g. `c(146, 38)`).
#' @param ladder_sizes Numeric vector with the sizes (bp) of the molecular
#'   weight marker (default a typical 50 bp ladder).
#' @param genotype_labels Character vector with the labels of the 3 sample
#'   lanes, in the order: uncut homozygote, heterozygote, cut homozygote.
#'
#' @return A `ggplot` object.
#' @export
simulate_gel <- function(amplicon_size, fragment_sizes,
                          ladder_sizes = c(50, 100, 150, 200, 250, 300, 400, 500),
                          genotype_labels = c("Homozygous WT", "Heterozygous", "Homozygous mutant")) {
  if (length(fragment_sizes) != 2) {
    stop("fragment_sizes must contain exactly 2 values (the two fragments generated by the cut).")
  }
  if (length(genotype_labels) != 3) {
    stop("genotype_labels must contain exactly 3 labels.")
  }

  gel_bands <- data.frame(Lane = integer(), Condition = character(), Size = numeric(), stringsAsFactors = FALSE)
  gel_bands <- rbind(gel_bands, data.frame(Lane = 1, Condition = "Marker (Ladder)", Size = ladder_sizes))
  gel_bands <- rbind(gel_bands, data.frame(Lane = 2, Condition = genotype_labels[1], Size = amplicon_size))
  gel_bands <- rbind(gel_bands, data.frame(Lane = 3, Condition = genotype_labels[2], Size = c(amplicon_size, fragment_sizes)))
  gel_bands <- rbind(gel_bands, data.frame(Lane = 4, Condition = genotype_labels[3], Size = fragment_sizes))

  gel_bands$Y_pos <- log10(gel_bands$Size)
  gel_bands$Intensity <- pmax(0.45, gel_bands$Size / amplicon_size)
  gel_bands$Intensity[gel_bands$Lane == 1] <- 0.8

  gel_top <- log10(max(ladder_sizes) * 1.4)
  gel_bottom <- log10(min(c(ladder_sizes, fragment_sizes)) * 0.7)
  well_top <- gel_top
  well_bottom <- log10(max(ladder_sizes) * 1.1)

  ladder_df <- gel_bands[gel_bands$Lane == 1, ]
  samples_df <- gel_bands[gel_bands$Lane > 1, ]

  ggplot2::ggplot(gel_bands) +
    ggplot2::geom_rect(
      ggplot2::aes(xmin = 0.5, xmax = 4.5, ymin = gel_bottom, ymax = gel_top),
      fill = "#0d0f12", color = "grey30", linewidth = 1
    ) +
    ggplot2::geom_rect(
      data = data.frame(X = 1:4),
      ggplot2::aes(xmin = X - 0.25, xmax = X + 0.25, ymin = well_bottom, ymax = well_top),
      fill = "#23272a", color = "grey60"
    ) +
    ggplot2::geom_segment(
      ggplot2::aes(x = Lane - 0.25, xend = Lane + 0.25, y = Y_pos, yend = Y_pos, alpha = Intensity),
      color = "#90EE90", linewidth = 3.5, lineend = "round"
    ) +
    ggplot2::geom_text(
      data = ladder_df,
      ggplot2::aes(x = 0.55, y = Y_pos, label = paste0(Size, " bp")),
      color = "#CCCCCC", size = 3.2, hjust = 0, fontface = "bold"
    ) +
    ggplot2::geom_text(
      data = samples_df,
      ggplot2::aes(x = Lane, y = Y_pos + 0.03, label = paste0(Size, " bp")),
      color = "#FFFFFF", size = 3.2, vjust = 0, fontface = "bold"
    ) +
    ggplot2::scale_x_continuous(breaks = 1:4, labels = c(
      "MW\n(Ladder)",
      paste0(genotype_labels[1], "\n(Uncut)"),
      paste0(genotype_labels[2], "\n(Both patterns)"),
      paste0(genotype_labels[3], "\n(Cut)")
    )) +
    ggplot2::labs(
      title = "Virtual agarose gel electrophoresis",
      subtitle = paste0("PCR-RFLP simulation | Base amplicon: ", amplicon_size, " bp"),
      x = "Loading lanes", y = "Electrophoretic migration (- -> +)"
    ) +
    ggplot2::scale_alpha_identity() +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      panel.grid = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_text(color = "grey40", size = 10, face = "italic"),
      axis.text.x = ggplot2::element_text(face = "bold", size = 10, color = "#2c3e50"),
      plot.title = ggplot2::element_text(face = "bold", size = 14, color = "#2c3e50"),
      plot.subtitle = ggplot2::element_text(color = "grey40", size = 11),
      plot.background = ggplot2::element_rect(fill = "white", color = NA)
    )
}
